### ISSUE TITLE
Return NIL for an empty section

### ISSUE THREAD

**Issue by fukamachi** [scymtym/parser.ini#2]
It returns `NIL` when no options are folloing in a section.

```common-lisp
(parser.ini:parse "[section]" 'list)
;=> NIL
;   NIL
;   T
```

Which means, it can't tell if the section exists or not.
For instance, I'm using this library for parsing `~/.aws/config` and `~/.aws/credentials` in aws-sdk-lisp.

Here's a code to parse them:
https://github.com/fukamachi/aws-sdk-lisp/blob/master/utils/config.lisp#L12-L18

It intends to raise an error if the specified AWS_PROFILE section doesn't exist in config files.
However, parser.ini returns `NIL` if it exists but no options 😕 

Here's the report by an user:
https://github.com/fukamachi/aws-sdk-lisp/issues/4#issuecomment-395728209

**Comment by scymtym** [comment]
I can add a special variable ``*keep-empty-sections?*`` that you can bind around ``parse`` calls:

```lisp
(let ((parser.ini:*keep-empty-sections?* t))
  (parser.ini:parse "[section]" 'list))
; => ((:SECTION NIL :NAME ("section") :BOUNDS (0 . 9)))
;    NIL
;    T
```

Would that work for you?

**Comment by fukamachi** [comment]
It’s fine to me :+1:
