### ISSUE TITLE
Error with comments starting with ";" (semicolons)

### ISSUE THREAD

**Issue by fukamachi** [scymtym/parser.ini#3]
parser.ini adopts `#` (shell like comment), however, `;` (semicolons) seems to be generally adopted in INI files.

> Semicolons (;) at the beginning of the line indicate a comment. Comment lines are ignored. 
https://en.wikipedia.org/wiki/INI_file#Comments

**Comment by fukamachi** [comment]
Reproducible code is here:

```common-lisp
(parser.ini:parse "; aaa
[section] option = value" 'list)
```

**Comment by scymtym** [comment]
Thanks for the report.

**Comment by fukamachi** [comment]
Thanks!
